### PR TITLE
NEWS: tag 1.5

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
moved to draft, want to get https://github.com/containers/fuse-overlayfs/pull/286 in first

**Comment by rhatdan** [comment]
#256 was merged

**Comment by giuseppe** [comment]
rebased

**Pull request merged**
