### PR TITLE
NEWS: tag 1.2

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@rhatdan this could be helpful for the NFS use case, as uid/gid/mode can be stored in an extended attribute

**Review by saschagrunert — APPROVED** [review]
LGTM :)

**Comment by rhatdan** [comment]
LGTM

**Comment by plopresti** [comment]
@giuseppe @rhatdan NFS does not support extended attributes until very -- and I mean very -- recently (https://stackoverflow.com/q/24629459/#comment113550932_47805199).

**Pull request merged**
