### PR TITLE
fuse-overlayfs: different performance tweaks

### PR DESCRIPTION
**Pull request by giuseppe**
this PR has different performance improvements, most notably, there is some initial support for threading.  Most of the code is still protected by a lock, so it runs on a single threaded, but operations like read/write/setattr/fsync can be dispatched on a different thread.

It is now possible to disable `fsync` that seems to slow `apt` quite significantly.  In general it is probably safer to run containers without access to fsync.

The new options can be configured in Podman through `~/.config/containers/storage.conf`.  I've got the  best results with this combination:

`mountopt = "threaded=0,fsync=0"`

### CODE REVIEW

**Comment by giuseppe** [comment]
this needs a fix in SELinux:

```
type=AVC msg=audit(1563197807.799:377): avc:  denied  { setattr } for  pid=7950 comm="fuse-overlayfs" name="183" dev="proc" ino=160867 scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=lnk_file permissive=0
```

**Comment by giuseppe** [comment]
> `type=AVC msg=audit(1563197807.799:377): avc: denied { setattr } for pid=7950 comm="fuse-overlayfs" name="183" dev="proc" ino=160867 scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=lnk_file permissive=0`

@rhatdan is it possible to enable it only for `/proc/self`?

**Comment by rhatdan** [comment]
Was this actually blocking?  Since this is an unconfined domain it should be allowed.  But it looks like a bogus AVC?

A process is attempting to change the attributes of something in /proc/self? The link file is fuse-overlayfs?  Is this more about the setattr should be on the thing the link points at?

**Comment by giuseppe** [comment]
the process inside the rootless container was blocked.  I'm using `/proc/self/FD` to change the ownership of a symlink.  It seems like the only possible way when dealing with symlinks and fds.

**Comment by rhatdan** [comment]
If this is a container process trying to make this change then it is running with the wrong label. unconfined_t versus container_t.

**Comment by rhatdan** [comment]
type=AVC msg=audit(1563197807.799:377): avc: denied { setattr } for pid=7950 comm="fuse-overlayfs" name="183" dev="proc" ino=160867 scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=lnk_file permissive=0

IE is this supposed to be 
container_t writing to unconfined_t lnk_file or
container_t writing to contianer_t lnk_file or 
the process running podman writing to the lnk_file, in which case it would be unconfined_t writing to unconfined_t lnk_file.

**Comment by rhatdan** [comment]
No problem allowing 
 container_t setattr to contianer_t lnk_file or
unconfined_t setattr to unconfined_t lnk_file

Problem with 
container_t setattr on unconfined_t lnk_file

**Comment by giuseppe** [comment]
I see.  fuse-overlayfs doesn't run in the container, only in its user+mount namespace created by podman

**Comment by giuseppe** [comment]
@rhatdan could we get the `unconfined_t setattr to unconfined_t lnk_file` fix for selinux?

With this PR fuse-overlayfs performs significantly better.

I've added some new options, such as disabling xattrs.  This helps with SELinux as we won't hit the FUSE file system with a getxattr for every operation.  Also, disabling fsync seems a sane default for containers, at least for the rootfs where fuse-overlayfs is used.  With this in place fuse-overlayfs performs better than native overlay in most cases.

Using `mountopt = "noxattrs=1,fsync=0,threaded=0"` with rootless podman I get:

```
$ /usr/bin/time -v podman  run --rm -ti ubuntu:18.04 sh -c 'apt update && apt install -y wine-development'
[.....]
	User time (seconds): 0.15
	System time (seconds): 0.31
	Percent of CPU this job got: 1%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:29.64
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 43416
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 4940
	Voluntary context switches: 4978
	Involuntary context switches: 84
	Swaps: 0
	File system inputs: 16
	File system outputs: 608
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

with root and native overlay:

```
# /usr/bin/time -v podman  run --rm -ti ubuntu:18.04 sh -c 'apt update && apt install -y wine-development'
[.....]
	User time (seconds): 0.22
	System time (seconds): 0.36
	Percent of CPU this job got: 1%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:38.17
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 43808
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 2
	Minor (reclaiming a frame) page faults: 14456
	Voluntary context switches: 7312
	Involuntary context switches: 186
	Swaps: 0
	File system inputs: 264
	File system outputs: 624
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

```

**Comment by rhatdan** [comment]
@wrabcak  Could you update selinux-policy for Fedora and RHEL7/RHEL8 with 
allow unconfined_domain self:lnk_file setattr;

**Comment by wrabcak** [comment]
Added to selinux-policy for F29, F30 and Rawhide:
https://github.com/fedora-selinux/selinux-policy/commit/444993df20a79e8694c28e5117d3f63a8fd995c8

**Comment by rhatdan** [comment]
Would have been a lot easier to review, if you did a lot of these as separate reviews and documented how they helped improve performance.

**Comment by mbargull** [comment]
Happy to see work fuse-overlayfs' performance.
I can't really comment on/review these changes, but was curious enough to compile and test this branch against a slow-running case I know of. Hopefully the following can be of some use.

This records the time taken to create a couple thousand folders (via `seq $count | xargs mkdir`) and remove them (via `find . -delete`) for the different storage drivers for `podman`:
<details><summary>

```sh
/usr/bin/fuse-overlayfs --version
/tmp/fuse-overlayfs-gh-88 --version
for storage_option in \
    --storage-driver=vfs \
    --storage-driver=overlay \
    --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88 \
    ; do
  printf \\n\\n
  for count in 1000 2000 20000 40000 80000 ; do
    podman --root="$(pwd)/containers" ${storage_option} run --rm -qit \
      --workdir=/test --env=count="${count}" --env=TIME="${storage_option} ${count} %S %U %e %C" \
      busybox sh -ec 'seq "${count}" | \time xargs mkdir && \time find . -delete ; printf \\n'
  done
  rm -rf ./containers
done | column -tLN storage,count,sys,user,wall,command -R storage,count,sys,user,wall
```
</summary>

```
fuse-overlayfs: version 0.4.2
FUSE library version 3.6.1
using FUSE kernel interface version 7.29
fusermount3 version: 3.6.1
fuse-overlayfs: version 0.4.2
FUSE library version 3.6.2
using FUSE kernel interface version 7.31
fusermount3 version: 3.6.1
                                                      storage  count    sys  user    wall  command             
                                                                                                               
                                                                                                               
                                         --storage-driver=vfs   1000   0.00  0.00    0.00  xargs    mkdir
                                         --storage-driver=vfs   1000   0.00  0.00    0.00  find     .          -delete
                                                                                                               
                                         --storage-driver=vfs   2000   0.00  0.00    0.00  xargs    mkdir
                                         --storage-driver=vfs   2000   0.01  0.00    0.01  find     .          -delete
                                                                                                               
                                         --storage-driver=vfs  20000   0.03  0.00    0.04  xargs    mkdir
                                         --storage-driver=vfs  20000   0.11  0.02    0.14  find     .          -delete
                                                                                                               
                                         --storage-driver=vfs  40000   0.07  0.01    0.09  xargs    mkdir
                                         --storage-driver=vfs  40000   0.16  0.10    0.28  find     .          -delete
                                                                                                               
                                         --storage-driver=vfs  80000   0.17  0.02    0.19  xargs    mkdir
                                         --storage-driver=vfs  80000   0.36  0.19    0.58  find     .          -delete
                                                                                                               
                                                                                                               
                                                                                                               
                                     --storage-driver=overlay   1000   0.00  0.00    0.00  xargs    mkdir
                                     --storage-driver=overlay   1000   0.00  0.00    0.00  find     .          -delete
                                                                                                               
                                     --storage-driver=overlay   2000   0.00  0.00    0.01  xargs    mkdir
                                     --storage-driver=overlay   2000   0.00  0.00    0.02  find     .          -delete
                                                                                                               
                                     --storage-driver=overlay  20000   0.08  0.00    0.09  xargs    mkdir
                                     --storage-driver=overlay  20000   0.14  0.04    0.19  find     .          -delete
                                                                                                               
                                     --storage-driver=overlay  40000   0.17  0.01    0.19  xargs    mkdir
                                     --storage-driver=overlay  40000   0.26  0.11    0.40  find     .          -delete
                                                                                                               
                                     --storage-driver=overlay  80000   0.36  0.02    0.39  xargs    mkdir
                                     --storage-driver=overlay  80000   0.49  0.26    0.80  find     .          -delete
                                                                                                               
                                                                                                               
                                                                                                               
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs   1000   0.01  0.00    0.07  xargs    mkdir
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs   1000   0.01  0.00    0.12  find     .          -delete
                                                                                                               
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs   2000   0.03  0.00    0.22  xargs    mkdir
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs   2000   0.05  0.00    0.38  find     .          -delete
                                                                                                               
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs  20000   1.77  0.17   15.23  xargs    mkdir
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs  20000   3.05  0.62   31.32  find     .          -delete
                                                                                                               
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs  40000   4.72  0.22   73.52  xargs    mkdir
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs  40000   7.53  1.78  149.06  find     .          -delete
                                                                                                               
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs  80000   9.03  0.61  342.64  xargs    mkdir
  --storage-opt=overlay.mount_program=/usr/bin/fuse-overlayfs  80000  13.89  3.20  673.05  find     .          -delete
                                                                                                               
                                                                                                               
                                                                                                               
  storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88   1000   0.01  0.00    0.05  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88   1000   0.01  0.00    0.09  find     .          -delete
                                                                                                               
  storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88   2000   0.02  0.00    0.15  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88   2000   0.03  0.01    0.24  find     .          -delete
                                                                                                               
  storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88  20000   0.89  0.04    7.10  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88  20000   1.47  0.42   13.53  find     .          -delete
                                                                                                               
  storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88  40000   2.76  0.31   34.43  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88  40000   5.36  1.07   67.84  find     .          -delete
                                                                                                               
  storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88  80000   6.97  0.37  202.25  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88  80000  11.73  3.18  401.59  find     .          -delete
                                                                                                               
```
</details>

`/tmp/fuseoverlayfs-gh-88` is created via the `Dockerfile.static` from this repository (changed to target this branch) with the state before the last push/GitHub outage.
Overall, speed seems to more or less double compared to the release version, which is nice. The superlinearily increasing time is still observable, though.

Regarding the new options: I have no idea (didn't think about/research it) whether setting `fsync=0`/`fsync=1` should/would affect this test case, but it seems only `threaded=0` vs `threaded=1` shows a difference:
<details>

```sh
|> podman --root="$(pwd)/containers" \
|>   --storage-opt='"overlay.mountopt=threaded=0,fsync=0","overlay.mount_program=/tmp/fuse-overlayfs-gh-88"' \
|>   run --rm -qit --workdir=/test --env=TIME='%S %U %e %C' \
|>   busybox sh -ec 'seq 20000 | \time xargs mkdir && \time find . -delete'
0.90 0.07 7.13 xargs mkdir
1.66 0.25 13.43 find . -delete
|> podman --root="$(pwd)/containers" \
|>   --storage-opt='"overlay.mountopt=threaded=0,fsync=1","overlay.mount_program=/tmp/fuse-overlayfs-gh-88"' \
|>   run --rm -qit --workdir=/test --env=TIME='%S %U %e %C' \
|>   busybox sh -ec 'seq 20000 | \time xargs mkdir && \time find . -delete'
0.94 0.04 7.18 xargs mkdir
1.62 0.35 13.52 find . -delete
|> podman --root="$(pwd)/containers" \
|>   --storage-opt='"overlay.mountopt=threaded=1,fsync=0","overlay.mount_program=/tmp/fuse-overlayfs-gh-88"' \
|>   run --rm -qit --workdir=/test --env=TIME='%S %U %e %C' \
|>   busybox sh -ec 'seq 20000 | \time xargs mkdir && \time find . -delete'
1.19 0.03 10.17 xargs mkdir
1.61 0.55 17.83 find . -delete
|> podman --root="$(pwd)/containers" \
|>   --storage-opt='"overlay.mountopt=threaded=1,fsync=1","overlay.mount_program=/tmp/fuse-overlayfs-gh-88"' \
|>   run --rm -qit --workdir=/test --env=TIME='%S %U %e %C' \
|>   busybox sh -ec 'seq 20000 | \time xargs mkdir && \time find . -delete'
1.10 0.11 10.30 xargs mkdir
1.76 0.51 18.03 find . -delete
```
</details>

**Comment by mbargull** [comment]
Re-ran the above with the latest changes from https://github.com/containers/fuse-overlayfs/pull/88/commits/59cd4c0ba45b339198977f7cf9757179023ce324 :
```
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0   1000  0.01  0.00  0.04  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0   1000  0.01  0.00  0.06  find     .          -delete
                                                                                                                    
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0   2000  0.02  0.00  0.09  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0   2000  0.04  0.00  0.13  find     .          -delete
                                                                                                                    
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0  20000  0.20  0.00  0.93  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0  20000  0.35  0.09  1.29  find     .          -delete
                                                                                                                    
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0  40000  0.38  0.02  1.87  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0  40000  0.71  0.19  2.59  find     .          -delete
                                                                                                                    
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0  80000  0.78  0.05  3.76  xargs    mkdir
--storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-gh-88-59cd4c0  80000  1.42  0.42  5.21  find     .          -delete
```
Some of those changes fixed the non-linear slowness -- massive improvement!

**Comment by rhatdan** [comment]
LGTM
We need to get this into Rawhide first and make sure it does not break anything...  Also put it up for fedora updates but make sure everyone on the team installs it.  Especially QE.  Need to quickly get it into CI/CD tests for podman.

**Comment by giuseppe** [comment]
@mbargull thanks a lot for your tests, I've opened a new PR that should improve the tests case you've reported above: https://github.com/containers/fuse-overlayfs/pull/89

For your test case, the new options should not make any difference, in particular `sync=0` is useful when there are too many `fsync(2)` happening on the file system, it seems to make a huge difference with `apt` and `dpkg`.

Could you re-run the test with #89?  In general I am curious about the previous released version of fuse-overlayfs vs the version in #89.

**Comment by giuseppe** [comment]
>  We need to get this into Rawhide first and make sure it does not break anything... Also put it up for fedora updates but make sure everyone on the team installs it. Especially QE. Need to quickly get it into CI/CD tests for podman.

I'll do that once https://bodhi.fedoraproject.org/updates/FEDORA-2019-b156bd756a is finally moved to stable and #89 is also merged

**Comment by mbargull** [comment]
> @mbargull thanks a lot for your tests, I've opened a new PR that should improve the tests case you've reported above: #89

With pleasure! Thanks for your work on this. I'll report in gh-91, comparing release `0.4.2`, gh-88, gh-89, and gh-91.

> For your test case, the new options should not make any difference, in particular `sync=0` is useful when there are too many `fsync(2)` happening on the file system

Right, makes sense, the `mkdir`/`rm` test case wouldn't necessarily sync, thanks.

**Comment by giuseppe** [comment]
Sorry I have just opened a new PR.  Could you just use that?  The intermediate ones don't make much sense to be tested separately

**Comment by mbargull** [comment]
Ah, didn't see comment. Will do, gimme a couple of minutes.

**Pull request merged**
