### PR TITLE
main: use openat2 where available

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by srd424** [comment]
Looks like this may change in systemd if https://github.com/systemd/systemd/pull/18342 gets merged..

**Comment by srd424** [comment]
systemd/systemd#18342 now merged and will presumably ship in v248; as the original check only landed in 247, it's probably not worth worrying too much about nasty workarounds in overlayfs?

**Comment by giuseppe** [comment]
> [systemd/systemd#18342](https://github.com/systemd/systemd/pull/18342) now merged and will presumably ship in v248; as the original check only landed in 247, it's probably not worth worrying too much about nasty workarounds in overlayfs?

yes I agree, if the system reports EPERM that must be handled as such.  ENOSYS is the correct error message in this case and it is good that it is fixed in systemd

**Pull request merged**
