### PR TITLE
fixes in error handling

### PR DESCRIPTION
**Pull request by eriksjolund**
I marked this PR as a draft because I haven't had the time to look into the details.
I hope to remove the draft status within 2 weeks.

### CODE REVIEW

**Comment by eriksjolund** [comment]
Hopefully the PR makes sense. fuse-overlayfs is a complex piece of software. I realised that only after starting writing the PR. It's tricky to know if an error should be returned or not in some places.

**Comment by eriksjolund** [comment]
I started a discussion thread in the libfuse project about the github workflow test failure 

* https://github.com/libfuse/libfuse/discussions/897

**Comment by eriksjolund** [comment]
The libfuse bug that caused a test failure has now been fixed

* https://github.com/libfuse/libfuse/pull/900

**Comment by rhatdan** [comment]
@eriksjolund @giuseppe What do we want to do with this one?

**Comment by eriksjolund** [comment]
> @eriksjolund @giuseppe What do we want to do with this one?

 I don't mind if you just close the PR. (I just want to give you this option because
the PR does not fix anything important)

**Pull request closed without merging**
