### PR TITLE
fuse-overlayfs: support some ioctls

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/fuse-overlayfs/issues/59

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Does fuse call into this function?

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
yes, it calls the `.ioctl` callback, that is registered to `ovl_ioctl`.

Let's wait for @ihucos comments before merging this

**Comment by ihucos** [comment]
> Let's wait for @ihucos comments before merging this

Thanks. One thing that I don't understand in the whole picture, is that apparently calling `fuse-overlayfs` by root seems to work (see output in issue), in the sense that the program (`pacman`) using the `ioctl` does not complain in that case. How is that possible, if currently `ioctl` is not implemented in `fuse-overlayfs`.

About comments on the pull request I can only offer bikeshedding: One thing that at least in theory could surprise applications are maybe `errno` codes. As a developer I would only expect the `errno` codes listed in the man page of `ioctl`. I this pull request it could for example return errnos returned by `openat`, like `ENOMEM`, which would be passed as return value of ioctl, which at least in it's man page, does not have `ENOMEM` listed as possible error. I am kind of new to low level system programming and can't say how strict these usually are.

Very generally as a `fuse-overlayfs` user I would favor strictness over compatibility and prefer an application running on top of `fuse-overlayfs` to fail always than only sometimes.

**Comment by giuseppe** [comment]
when it is running as root, if I try `chattr +i`, I get `chattr: Function not implemented while reading flags on merged/i`.  With the patch I get the correct behaviour.

The errno list in the man page is never exhaustive, there are many cases where syscalls can fail with errors not listed there.

**Comment by ihucos** [comment]
LGTM :-)

**Pull request merged**
