### PR TITLE
musl fix and various tweaks

### PR DESCRIPTION
**Pull request by agherzan**
1. fixes build error with musl (limits.h)
2. clarifies FUSE version in configure error
3. cleans up utils.h

### CODE REVIEW

**Comment by agherzan** [comment]
> LGTM

Thanks @rhatdan. Anything left to ge this merged? An additional minor release would be useful.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
sorry for missing this PR for so long

**Comment by agherzan** [comment]
Thanks @giuseppe.

**Pull request merged**
