### PR TITLE
set_attrs: don't require write to S_IFREG

### PR DESCRIPTION
**Pull request by nwf**
It's perfectly possible to set attributes by being the file's owner; one
does not need write access to the contents.

### CODE REVIEW

**Comment by giuseppe** [comment]
looks like the tests are failing

**Comment by giuseppe** [comment]
`ftruncate` requires the file to be open for writing

**Comment by giuseppe** [comment]
@nwf are you still working on this PR?

**Comment by nwf** [comment]
No, my day job has had me busy with other things.  Please feel free to adjust the patch as appropriate and close the PR.

**Comment by rhatdan** [comment]
@giuseppe What do you want to do with this?

**Comment by nwf** [comment]
FWIW, this is relevant because tools like tar, for example, create a file and chmod away all permissions and then attempt to modify metadata.  When that happens within a fuse-overlayfs mount, the chmod() passes through, zeroing permissions, and the subsequent modifications trigger new open()s that fail.

**Comment by giuseppe** [comment]
I'll take a look at it.  It is not an issue with rootless containers, as fuse-overlayfs runs in a namespace so it still works

**Comment by giuseppe** [comment]
@nwf I've opened https://github.com/containers/fuse-overlayfs/pull/120 and I've kept you as author, so please let me know if it looks fine for you before we can merge it :-)

**Comment by nwf** [comment]
Replaced by #120.

**Pull request closed without merging**
