### PR TITLE
*: some build hints and static link example

### PR DESCRIPTION
**Pull request by vbatts**
Fixes: #9 

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
that built container image is 774Mb, but the binary is only 2.1Mb not-stripped and 1.2Mb stripped :-)

**Comment by vbatts** [comment]
updated so that args append to the entrypoint

**Comment by vbatts** [comment]
```shell
sudo podman run -it --rm -v $HOME:$HOME -v $HOME/upper:/upper -v $HOME/workdir:/workdir -v $HOME/merged:/merged --device /dev/fuse --cap-add SYS_ADMIN fuse-overlayfs -o lowerdir=$HOME,upperdir=/upper,workdir=/workdir /merged
```
works, but would be neater with #11 in place

**Comment by giuseppe** [comment]
thanks a lot for working on this.

**Pull request merged**
