### PR TITLE
fuse-overlayfs: fix a fd leak when creating new files

### PR DESCRIPTION
**Pull request by giuseppe**
an issue introduced by last changes

### CODE REVIEW

**Comment by giuseppe** [comment]
I'll continue do testing and tag a new release in the next few days.

**Comment by mbargull** [comment]
- `/tmp/fuse-overlayfs-7bc2dd9`: release `0.4.2` compiled with `Dockerfile.static`
- `/tmp/fuse-overlayfs-4e32e89`:current state fo this PR compiled with `Dockerfile.static`
<details open><summary>

```sh
for storage_option in \
    --storage-driver=overlay \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-7bc2dd9 \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-4e32e89 \
    ; do
  printf \\n
  for count in 10000 20000 ; do
    podman --runroot=/tmp/containers --root=/tmp/containers ${storage_option} run --rm -qit \
      --workdir=/test --env=count="${count}" --env=TIME="${storage_option##*=} ${count} %S %U %e %C" \
      busybox sh -ec 'seq "${count}" | \time xargs mkdir -p && \time find . -delete ; printf \\n'
  done
  rm -rf /tmp/containers
done | column -tLN storage,count,sys,user,wall,command -R storage,count,sys,user,wall
```
</summary>

```
                    storage  count   sys  user   wall  command         
                                                                       
                    overlay  10000  0.04  0.00   0.05  xargs    mkdir  -p
                    overlay  10000  0.06  0.02   0.09  find     .      -delete
                                                                       
                    overlay  20000  0.07  0.01   0.10  xargs    mkdir  -p
                    overlay  20000  0.14  0.04   0.20  find     .      -delete
                                                                       
                                                                       
/tmp/fuse-overlayfs-7bc2dd9  10000  0.44  0.00   3.61  xargs    mkdir  -p
/tmp/fuse-overlayfs-7bc2dd9  10000  0.67  0.22   6.93  find     .      -delete
                                                                       
/tmp/fuse-overlayfs-7bc2dd9  20000  1.61  0.05  14.59  xargs    mkdir  -p
/tmp/fuse-overlayfs-7bc2dd9  20000  2.50  0.60  29.66  find     .      -delete
                                                                       
                                                                       
/tmp/fuse-overlayfs-4e32e89  10000  0.10  0.00   0.28  xargs    mkdir  -p
/tmp/fuse-overlayfs-4e32e89  10000  0.18  0.04   0.46  find     .      -delete
                                                                       
/tmp/fuse-overlayfs-4e32e89  20000  0.20  0.00   0.57  xargs    mkdir  -p
/tmp/fuse-overlayfs-4e32e89  20000  0.35  0.12   0.96  find     .      -delete
```
</details>

**Comment by mbargull** [comment]
For a more real-world test case, here is one for `conda`, the package manager:
This prepares (as in downloads/extracts everything beforehand) a container image with a certain package build that is known to contain around 7800 (mostly small) files, `openssl=1.1.1a=h7b6447c_0`. It then times the installation and removal of said package.

Now, the "fun" part is that newer versions of `conda` have a bug/regression/misconception such that for every single file it removes, it (recursively) checks whether the parent directories are empty and can be removed as well. Ergo, it is excruciatingly slow if the check for empty folders is slow like it is in the current release version of `fuse-overlayfs`. The simplified test case for this is the `find . -delete` one above.
(Of course `conda` is to be blamed here foremost and will be fixed in the future. It has just been a whole lot of months since I've been involved in `conda`'s development and thus didn't had the change to do so already...)

As above:

- `/tmp/fuse-overlayfs-7bc2dd9`: release `0.4.2` compiled with `Dockerfile.static`
- `/tmp/fuse-overlayfs-4e32e89`: current state fo this PR compiled with `Dockerfile.static`

<details><summary><code>conda 4.5.12</code></summary>

<details open><summary>

```sh
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay from -q --name=mc3 continuumio/miniconda3:4.5.12
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 apt-get update -qq
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 apt-get install -qqy time >/dev/null
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 conda create -qyne --no-deps openssl=1.1.1a=h7b6447c_0 >/dev/null
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 conda remove -qyne --force openssl >/dev/null
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay commit -q --rm mc3 mc3-img

for storage_option in \
    --storage-driver=overlay \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-7bc2dd9 \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-4e32e89 \
    ; do
  printf \\n
  podman --runroot=/tmp/containers --root=/tmp/containers "${storage_option}" run --rm -it \
    --env=TIME="${storage_option##*=} %S %U %e %C" mc3-img \
    bash -eulc '
      conda activate base
      \time conda install -qyne --no-deps openssl=1.1.1a=h7b6447c_0 >/dev/null
      \time conda remove -qyne --force openssl >/dev/null
    '
done | column -tLN storage,sys,user,wall,command -R storage,sys,user,wall
rm -rf /tmp/containers
```
</summaty>

```
mc3
debconf: delaying package configuration, since apt-utils is not installed
473a3c39108c874ababae732e8deda77f79afd57d89150c3182a2535ec081b89
                    storage   sys  user   wall  command                             
                                                                                    
                    overlay  0.27  2.46   2.75  conda    install  -qyne  --no-deps  openssl=1.1.1a=h7b6447c_0
                    overlay  0.24  1.16   1.42  conda    remove   -qyne  --force    openssl
                                                                                    
/tmp/fuse-overlayfs-7bc2dd9  0.43  2.94   8.36  conda    install  -qyne  --no-deps  openssl=1.1.1a=h7b6447c_0
/tmp/fuse-overlayfs-7bc2dd9  0.86  2.65  21.07  conda    remove   -qyne  --force    openssl
                                                                                    
/tmp/fuse-overlayfs-4e32e89  0.28  2.68   3.85  conda    install  -qyne  --no-deps  openssl=1.1.1a=h7b6447c_0
/tmp/fuse-overlayfs-4e32e89  0.34  1.29   2.07  conda    remove   -qyne  --force    openssl
```
</details>
</details>


<details><summary><code>conda 4.6.14</code></summary>

<details open><summary>

```sh
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay from -q --name=mc3 continuumio/miniconda3:4.6.14
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 apt-get update -qq
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 apt-get install -qqy time >/dev/null
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 conda create -qyne --no-deps openssl=1.1.1a=h7b6447c_0 >/dev/null
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay run mc3 conda remove -qyne --force openssl >/dev/null
buildah --runroot=/tmp/containers --root=/tmp/containers --storage-driver=overlay commit -q --rm mc3 mc3-img

for storage_option in \
    --storage-driver=overlay \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-7bc2dd9 \
    --storage-opt=overlay.mount_program=/tmp/fuse-overlayfs-4e32e89 \
    ; do
  printf \\n
  podman --runroot=/tmp/containers --root=/tmp/containers "${storage_option}" run --rm -it \
    --env=TIME="${storage_option##*=} %S %U %e %C" mc3-img \
    bash -eulc '
      conda activate base
      \time conda install -qyne --no-deps openssl=1.1.1a=h7b6447c_0 >/dev/null
      \time conda remove -qyne --force openssl >/dev/null
    '
done | column -tLN storage,sys,user,wall,command -R storage,sys,user,wall
rm -rf /tmp/containers
```
</summary>

```
mc3
debconf: delaying package configuration, since apt-utils is not installed
89d00d1bb9768a17f4d50a1cde25ec56405a56fb346906e9b007ca4a2c480f9e
                    storage   sys  user    wall  command                             
                                                                                     
                    overlay  0.26  2.40    2.67  conda    install  -qyne  --no-deps  openssl=1.1.1a=h7b6447c_0
                    overlay  3.92  3.78    7.73  conda    remove   -qyne  --force    openssl
                                                                                     
/tmp/fuse-overlayfs-7bc2dd9  0.44  2.84    8.52  conda    install  -qyne  --no-deps  openssl=1.1.1a=h7b6447c_0
/tmp/fuse-overlayfs-7bc2dd9  6.66  8.61  278.95  conda    remove   -qyne  --force    openssl
                                                                                     
/tmp/fuse-overlayfs-4e32e89  0.31  2.61    3.74  conda    install  -qyne  --no-deps  openssl=1.1.1a=h7b6447c_0
/tmp/fuse-overlayfs-4e32e89  3.11  4.19   10.01  conda    remove   -qyne  --force    openssl
```
</details>
</details>

**Comment by giuseppe** [comment]
thanks a lot for your tests.  This is very valuable data!  fuse-overlayfs is now quite optimized, so there is not much more, I guess, that it can do.  What kernel are you using?

A few things I've noticed:

1) disabling fsync helps a lot in real world use cases.  When building a container, it doesn't matter that the files are not synced to the storage while being installed, because in case of failure the container image will be thrown away and rebuild.  This is why I've added the `fsync=0` option.

2) If the kernel is new enough, FUSE supports using `splice(2)` for copying data around.  There was an issue in libfuse where it wasn't using the full available size for a pipe, this makes also a difference when copying/reading big files as it doesn't allow `splice(2)` to be used in most cases, I've opened a PR to address the issue and it was merged a couple of days ago: https://github.com/libfuse/libfuse/pull/438
You can simply work-around it for now with something like `echo 10485760 > /proc/sys/fs/pipe-max-size` as root.

3) `noatime` should also improve the performance, as we won't need to update the atime for each inode that is accessed.  I've not yet had time to look at it and check if it has any real effect.

4) tweaking `max_write` could also give different numbers.

3/4 are more notes for myself at this point, but if you'd like to try with a better setup for fuse-overlayfs, I'd suggest to enable 1 and2.  I've tried with apt-get and it seems to make a huge difference.

**Comment by rhatdan** [comment]
LGTM

**Comment by mbargull** [comment]
> fuse-overlayfs is now quite optimized, so there is not much more, I guess, that it can do.

:tada: 

> What kernel are you using?

```sh
|> uname -srmo
Linux 4.19.59-1-MANJARO x86_64 GNU/Linux
```
If you need numbers for other kernel versions, I should be able to rather effortlessly switch to any other LTS series (`3.16`, `4.4`, `4.9`, `4.14`) or newer versions (`5.1`, `5.2` `5.3rc1`).

> And what options have you used to build fuse-overlayfs?

Just the defaults from `Dockerfile.static`:
```sh
|> sed 's|RUN git clone .*fuse-overlayfs.*|COPY ./ ./fuse-overlayfs\nRUN \\|' Dockerfile.static
FROM registry.fedoraproject.org/fedora:latest
WORKDIR /build
RUN dnf update -y && \
    dnf install -y git make automake autoconf gcc glibc-static meson ninja-build clang

RUN git clone https://github.com/libfuse/libfuse && \
    cd libfuse && \
    mkdir build && \
    cd build && \
    LDFLAGS="-lpthread" meson --prefix /usr -D default_library=static .. && \
    ninja && \
    ninja install

COPY ./ ./fuse-overlayfs
RUN \
    cd fuse-overlayfs && \
    sh autogen.sh && \
    LIBS="-ldl" LDFLAGS="-static" ./configure --prefix /usr && \
    make && \
    make install
USER 1000
ENTRYPOINT ["/usr/bin/fuse-overlayfs","-f"]
```
Since that Dockerfile uses `git clone https://github.com/libfuse/libfuse` and I built it with a fresh cache, `libfuse` included your patch.

I ran that on a
```sh
|> grep -m1 model\ name /proc/cpuinfo
model name	: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
```
and to get reasonably consistent results (read: really, wanting to get away with \*cough\* "statistics" \*cough\* with sample size 1 ...):
- `--root` pointed to a directory on a `tmpfs` mount point,
- reduced CPU power-saving-induced variance with
  ```sh
  |> cat /sys/devices/system/cpu/cpu0/cpufreq/{scaling_governor,energy_performance_preference}
  performance
  balance_performance
  ```
- for consistency with comparing to `--storage-driver=overlay` I just ran everything as `root` (okay, pure laziness involved too, of course ;) )

----
> disabling fsync helps a lot in real world use cases.

If you want to, you can point me to one of those `apt` examples to run on my setup.
However, to make sure I understand correctly: Do speed differences from enabling/disabling `fsync` come mainly from the actual file system/hardware synchronization (i.e., actual I/O work, not just CPU time and main memory access)? I didn't see any measurable difference for `fsync=1`/`fsync=0` at all -- but that was on a RAM disk or NVMe SSD.
Though, if you are very interested in `fsync`-related numbers, I could just hook up an external hard drive via an USB 2.0 cable to get something slow to run on.

> When building a container, it doesn't matter that the files are not synced to the storage while being installed, because in case of failure the container image will be thrown away and rebuild. This is why I've added the fsync=0 option.

Sounds reasonable, thanks for the explanation!

----
> \[...\] `splice` \[...\] `noatime` \[...\] `max_write`

Changing those didn't show any difference outside the measuring inaccuracy.

**Comment by giuseppe** [comment]
> If you need numbers for other kernel versions, I should be able to rather effortlessly switch to any other LTS series (`3.16`, `4.4`, `4.9`, `4.14`) or newer versions (`5.1`, `5.2` `5.3rc1`).

FUSE has got some nice performance improvements in 5.1 that could make a difference compared to 4.x.

**Comment by mbargull** [comment]
Interestingly enough, I get slightly worse numbers on 5.2 for the `find . -delete` (thus also `conda=4.6.14`) case:
<details>

```sh
uname -srmo

root=/tmp/containers
fuse_overlayfs_bin='/home/mbargull/code/src/containers/fuse-overlayfs-56cc4d3'

"${fuse_overlayfs_bin}" --version

for storage in \
    '--storage-driver=vfs' \
    '--storage-driver=overlay' \
    "--storage-opt=overlay.mount_program=${fuse_overlayfs_bin}" \
    ; do
  rm -rf "${root}"
  printf '\n%s\n' "${storage}"

  buildah_() {
    buildah \
      --runroot="${root}" --root="${root}" "${storage}" \
      "${@}"
  }

  buildah_ rm tmp >/dev/null 2>&1 || true
  buildah_ from -q --name=tmp busybox >/dev/null
  buildah_ run tmp sh -ec '
    export TIME="%S %U %e %C"
    mkdir test && cd test
    \time seq 200000 | \time xargs mkdir -p
    \time find . -delete
  '

  buildah_ rm tmp >/dev/null 2>&1 || true
  buildah_ from -q --name=tmp continuumio/miniconda3:4.5.12 >/dev/null
  buildah_ run tmp apt-get update -qq
  buildah_ run tmp apt-get install -qqy time >/dev/null 2>&1
  buildah_ run tmp conda create -qyne --no-deps openssl=1.1.1a=h7b6447c_0 qt=5.9.7=h5867ecd_1 >/dev/null
  buildah_ run tmp conda remove -qyne --force openssl qt >/dev/null

  buildah_ run tmp bash -eulc '
    export TIME="%S %U %e %C"

    run_test() {
      conda search conda >/dev/null
      conda --version
      \time conda install -qyne --no-deps openssl=1.1.1a=h7b6447c_0 qt=5.9.7=h5867ecd_1 >/dev/null
      \time conda remove -qyne --force openssl qt >/dev/null
    }
    conda activate base
    CONDA_AGGRESSIVE_UPDATE_PACKAGES= conda install --no-deps conda=4.5.12 -qy >/dev/null
    run_test
    CONDA_AGGRESSIVE_UPDATE_PACKAGES= conda install --no-deps conda=4.6.14 -qy >/dev/null
    run_test
  '

done
```

</details>

```
Linux 4.19.60-1-MANJARO x86_64 GNU/Linux		      |	Linux 5.2.2-1-MANJARO x86_64 GNU/Linux
fuse-overlayfs: version v0.4.1-98-g56cc4d3			fuse-overlayfs: version v0.4.1-98-g56cc4d3
FUSE library version 3.6.2					FUSE library version 3.6.2
using FUSE kernel interface version 7.31			using FUSE kernel interface version 7.31
fusermount3 version: 3.6.1					fusermount3 version: 3.6.1

--storage-driver=vfs						--storage-driver=vfs
0.00 0.10 0.46 seq 200000				      |	0.00 0.10 0.32 seq 200000
0.41 0.05 0.48 xargs mkdir -p				      |	0.23 0.09 0.33 xargs mkdir -p
0.86 0.49 1.41 find . -delete				      |	0.89 0.63 1.59 find . -delete
conda 4.5.12							conda 4.5.12
0.29 4.67 4.97 conda install -qyne --no-deps openssl=1.1.1a=h |	0.28 4.65 4.94 conda install -qyne --no-deps openssl=1.1.1a=h
0.31 1.82 2.15 conda remove -qyne --force openssl qt	      |	0.26 1.87 2.14 conda remove -qyne --force openssl qt
conda 4.6.14							conda 4.6.14
0.38 4.57 4.96 conda install -qyne --no-deps openssl=1.1.1a=h |	0.32 4.61 4.95 conda install -qyne --no-deps openssl=1.1.1a=h
2.41 4.35 6.79 conda remove -qyne --force openssl qt	      |	2.28 4.50 6.81 conda remove -qyne --force openssl qt

--storage-driver=overlay					--storage-driver=overlay
0.00 0.10 0.90 seq 200000				      |	0.00 0.11 0.76 seq 200000
0.88 0.04 0.94 xargs mkdir -p				      |	0.68 0.09 0.79 xargs mkdir -p
1.31 0.51 1.94 find . -delete				      |	1.38 0.66 2.20 find . -delete
conda 4.5.12							conda 4.5.12
0.40 4.77 5.18 conda install -qyne --no-deps openssl=1.1.1a=h |	0.42 4.77 5.21 conda install -qyne --no-deps openssl=1.1.1a=h
0.42 1.94 2.37 conda remove -qyne --force openssl qt	      |	0.41 1.96 2.40 conda remove -qyne --force openssl qt
conda 4.6.14							conda 4.6.14
0.42 4.69 5.11 conda install -qyne --no-deps openssl=1.1.1a=h |	0.44 4.69 5.15 conda install -qyne --no-deps openssl=1.1.1a=h
3.82 4.63 8.49 conda remove -qyne --force openssl qt	      |	4.05 4.57 8.65 conda remove -qyne --force openssl qt

--storage-opt=overlay.mount_program=/home/mbargull/code/src/c	--storage-opt=overlay.mount_program=/home/mbargull/code/src/c
0.00 0.13 5.24 seq 200000				      |	0.00 0.13 5.15 seq 200000
1.91 0.10 5.49 xargs mkdir -p				      |	2.03 0.14 5.39 xargs mkdir -p
3.57 0.97 9.22 find . -delete				      |	4.57 0.94 10.37 find . -delete
conda 4.5.12							conda 4.5.12
0.65 4.94 6.59 conda install -qyne --no-deps openssl=1.1.1a=h |	0.68 4.94 6.67 conda install -qyne --no-deps openssl=1.1.1a=h
0.74 2.11 3.74 conda remove -qyne --force openssl qt	      |	0.97 2.06 3.98 conda remove -qyne --force openssl qt
conda 4.6.14							conda 4.6.14
0.65 4.80 6.33 conda install -qyne --no-deps openssl=1.1.1a=h |	0.70 4.78 6.36 conda install -qyne --no-deps openssl=1.1.1a=h
3.44 4.99 11.79 conda remove -qyne --force openssl qt	      |	4.63 5.16 13.37 conda remove -qyne --force openssl qt
```

Interesting parts:
- on 5.2.2, `overlay` spends less time in kernel mode for `mkdir` but more time in user mode for `mkdir` as well as `find . -delete`:
  ```
  --storage-driver=overlay					--storage-driver=overlay
  0.00 0.10 0.90 seq 200000				      |	0.00 0.11 0.76 seq 200000
  0.88 0.04 0.94 xargs mkdir -p				      |	0.68 0.09 0.79 xargs mkdir -p
  1.31 0.51 1.94 find . -delete				      |	1.38 0.66 2.20 find . -delete
  ```
- `fuse-overlayfs` spends more time in kernel mode with 5.2.2:
  ```
  --storage-opt=overlay.mount_program=/home/mbargull/code/src/c	--storage-opt=overlay.mount_program=/home/mbargull/code/src/c
  0.00 0.13 5.24 seq 200000				      |	0.00 0.13 5.15 seq 200000
  1.91 0.10 5.49 xargs mkdir -p				      |	2.03 0.14 5.39 xargs mkdir -p
  3.57 0.97 9.22 find . -delete				      |	4.57 0.94 10.37 find . -delete
  ```

**Pull request merged**
